FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD crm-protocol-0.0.1-SNAPSHOT.jar crm-protocol.jar
RUN sh -c 'touch /crm-protocol.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -jar /crm-protocol.jar" ]